// <auto-generated />
namespace LagunaShoreResort2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class salescontract_numberpayments_deleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(salescontract_numberpayments_deleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201603252052364_salescontract_numberpayments_deleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
