// <auto-generated />
namespace LagunaShoreResort2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class refundNullableDepsits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refundNullableDepsits));
        
        string IMigrationMetadata.Id
        {
            get { return "201602240005187_refundNullableDepsits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
