// <auto-generated />
namespace LagunaShoreResort2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tmRequestToAccountat_nulleable_false : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tmRequestToAccountat_nulleable_false));
        
        string IMigrationMetadata.Id
        {
            get { return "201606011954526_tmRequestToAccountat_nulleable_false"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
