// <auto-generated />
namespace LagunaShoreResort2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relation_condo_RSC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relation_condo_RSC));
        
        string IMigrationMetadata.Id
        {
            get { return "201611072241211_relation_condo_RSC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
