// <auto-generated />
namespace LagunaShoreResort2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedFiedl_Deposit_RealState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedFiedl_Deposit_RealState));
        
        string IMigrationMetadata.Id
        {
            get { return "201612182150156_addedFiedl_Deposit_RealState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
