// <auto-generated />
namespace LagunaShoreResort2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class salesMember_requieredFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(salesMember_requieredFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201604080510120_salesMember_requieredFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
