// <auto-generated />
namespace LagunaShoreResort2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newField_SalesContact_RealStateContracts_InitialHOAPayment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newField_SalesContact_RealStateContracts_InitialHOAPayment));
        
        string IMigrationMetadata.Id
        {
            get { return "201612312053302_newField_SalesContact_RealStateContracts_InitialHOAPayment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
