// <auto-generated />
namespace LagunaShoreResort2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newEntity_HOAFee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newEntity_HOAFee));
        
        string IMigrationMetadata.Id
        {
            get { return "201701120224000_newEntity_HOAFee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
